### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by tyrw** [KevinHoughton/vue-scroll-to#3]
This will be significantly more useful to many devs without the jQuery dependency.  

Looks like this library and vue-scrollTo both have jQuery dependency.  I suspect that first one to remove it will see an uptick in adoption.

**Comment by KevinHoughton** [comment]
Hey @tyrw,

I've just removed the dependency, scrolling is not yet as smooth as it used to be but will be fixed in the near future. Thanks!
