### ISSUE TITLE
Cannot read property el. of undefined

### ISSUE THREAD

**Issue by aslak01** [KevinHoughton/vue-scroll-to#4]
Hey,

I've updated from vue-cli's simple webpack to the full webpack, and I'm adding back functionality. Trying to add this component, I'm getting an error, although my code is nearly the same as before. "Cannot read property el of undefined." 

The only thing I've coded differently is that I did "import vueScrollTo from 'vue-scroll-to'" and Vue.use(VueScrollTo) instead of the import statement specified in the readme (which failed in the vue cli webpack setup).

**Comment by KevinHoughton** [comment]
Can you give me some of the code you used so I can try reproduce the error?

**Comment by aslak01** [comment]
Not sure what parts of the code are helpful. These are the sections where I reference vue-scroll-to.

main.js 
```
import Vue from 'vue'
import App from './App'
... 
import vueScrollTo from 'vue-scroll-to'
Vue.use(vueScrollTo)
...
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App },
  store: store
})
```

component.vue
```
<template>
  <div class="hero">
    <nav class="hovednav clearfix noselect" :class="navbarClasses">
      <a href="#" v-scroll-to="'#sec1'" class="hovednav--enhet">Sec 1</a>
      <a href="#" v-scroll-to="'#sec2'" class="hovednav--enhet">Sec 2</a>
    </nav>
  </div>
</template>
```

**Comment by irhtml** [comment]
Im having this exact issue

**Comment by KevinHoughton** [comment]
@aslak01 try this:
`
v-scroll-to="#sec1, 0px"`

**Comment by davidnash** [comment]
I'm having the same issue, if I use
`v-scroll-to="#sec1, 0px"`

I get 'Errror compiling template' with:
`- invalid expression: v-scroll-to="#sec1, 0px"`

If I use `v-scroll-to="'#sec1, 0px'"` the template compiles but then I get
`TypeError: Cannot read property 'el' of undefined`
when I click the scroll-to element.

**Comment by KevinHoughton** [comment]
For version 2.0.1 it's required to combine the classname and padding within two single quotes.

Example:

`<a href="#" v-scroll-to="'.test, 30px'">Test</a>`
