### ISSUE TITLE
ES2015 syntax breaks older browsers

### ISSUE THREAD

**Issue by hjr555** [KevinHoughton/vue-scroll-to#7]
Unfortunately, the ES2015 syntax introduced in v2.1.0 breaks compatibility for older browsers that do not support it.
In my case, it was Safari 9 on iOS9.

**Comment by GerkinDev** [comment]
It would have been better to introduce bundling tools, such as Parcel, Rollup or Webpack, to continue using modern syntax and output a more widely compatible script. IMHO this merge should be reverted.

Legacy constraints should not influence how code is made, but what compilation do...
